image:
  file: .gitpod.Dockerfile

tasks:
  - name: client
    before: cd client
    init: npm install
    command: npm start

  - name: posts
    before: cd posts
    init: npm install
    command: npm start

  - name: comments
    before: cd comments
    init: npm install
    command: npm start
